### ISSUE TITLE
Not able to create a defect from Azure DevOPs via Pulse

### ISSUE THREAD

**Issue by mdshariq2009** [Tricentis/qTest.Integration.Pulse#21]
Defects are not syncing as we do not have any procedure to create a new defect in Azure DevOps va pulse and that defect should go to qTest like we are doing from qTest to Azure.

## Expected Behavior
When a developer creates a defect in Azure DevOps, it should automatically go to the qTest via Pulse. If setup.

## Current Behavior
The developer created a defect in Azure DevOps which did not exist in the qTest. So, the QA team did not know about this defect.

## Your Environment

* Pulse Version used: 2023.6.0
* Environment (e.g. OP or OD):

**Comment by qaschris** [comment]
The ADO integration does not support creation of defects in ADO flowing to qTest, only updates on existing defects imported from qTest via this integration.  The are the supported features as per the [documentation](https://github.com/Tricentis/qTest.Integration.Pulse/blob/master/qtest/azure-devops/README.md):

- Automatically create new qTest Requirement when a new work item is created in Azure DevOps
- Automatically update qTest Requirement when the corresponding work item is updated in Azure DevOps
- Automatically delete qTest Requirement when the corresponding work item is deleted in Azure DevOps
- Automatically create new Azure DevOps Bug when a new Defect is created in qTest
- Automatically update qTest Defect when the corresponding Bug is updated in Azure DevOps
